trigger:
  branches:
    include:
      - main
      - infra   # or whichever branch you use for infra changes
  paths:
    include:
      - terraform/**   # only run when files under terraform/ change

pool:
  name: 'azureagent'

stages:
- stage: Terraform
  displayName: "Provision AKS with Terraform"
  jobs:
  - job: TerraformJob
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.5.7'

    - script: |
        terraform init
        terraform plan -out=tfplan
      workingDirectory: terraform
      displayName: 'Terraform Init & Plan'

    - script: |
        terraform apply -auto-approve tfplan
      workingDirectory: terraform
      displayName: 'Terraform Apply'
